### ISSUE TITLE
Anyone have working example?

### ISSUE THREAD

**Issue by iamsvmohan-1** [preko96/complete-mentions#2]
Please add an example for this library

Also remove trigger and add tag in readme which has code example

**Comment by preko96** [comment]
Hey there, just about to write a few examples

**Comment by preko96** [comment]
@iamsvmohan-1 Just created a few examples and an expo snack, if got any other question just let me know.

**Comment by ghost** [comment]
> @iamsvmohan-1 Just created a few examples and an expo snack, if got any other question just let me know.

thank you so much!

**Comment by ghost** [comment]
Please replace fontweight with proper values in your examples.
